### ISSUE TITLE
How to fix JSTL error in Jastow?

### ISSUE THREAD

**Issue by gencube** [undertow-io/jastow#21]
```2015-09-30-11:05:06:548 - ERROR - LoggingExceptionHandler - UT005023: Exception handling request to /jee7eg/index.jsp
org.apache.jasper.JasperException: JBWEB004113: The absolute uri: http://java.sun.com/jsp/jstl/core cannot be resolved in either web.xml or the jar files deployed with this application
    at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:57)
    at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:278)
    at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:75)
    at org.apache.jasper.compiler.TagLibraryInfoImpl.generateTLDLocation(TagLibraryInfoImpl.java:218)
    at org.apache.jasper.compiler.TagLibraryInfoImpl.<init>(TagLibraryInfoImpl.java:124)
...```

**Comment by gencube** [comment]
The following dependency had been added to pom.xml
```xml

<repositories>       
        <repository>
            <id>redhat.com</id>
            <url>http://maven.repository.redhat.com/techpreview/all/</url>
        </repository>       
    </repositories>

        <!-- Jasper+Undertow for JSP -->
        <dependency>
            <groupId>io.undertow.jastow</groupId>
            <artifactId>jastow</artifactId>
            <version>2.0.0.Beta3</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.spec.javax.servlet.jstl</groupId>
            <artifactId>jboss-jstl-api_1.2_spec</artifactId>
            <version>1.0.6.Final-redhat-1</version>
        </dependency>
```

**Comment by gencube** [comment]
https://github.com/gencube/Jee7EgJastow

**Comment by ctomc** [comment]
you should be using jboss-jstl-api_1.2_spec version 1.1.x for usage with servlet 3.1 implementations such as undertow.

**Comment by ctomc** [comment]
pretty much all reason for your problems lies here https://github.com/gencube/Jee7EgJastow/blob/master/src/main/java/mi/webmach/jee/WebXml.java#L95
where you don't configure tld mappings as pass empty map.

for reference you can look at how we configure it in WildFly during deployment
https://github.com/wildfly/wildfly/blob/master/undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentInfoService.java#L638-L644

**Comment by gencube** [comment]
Hi The code fragment shown is implicating too many dependencies indirectly and I needed to do a wild goose chase. 

What do I change this line to make it works?
```java
 JspServletBuilder.setupDeployment(info, new HashMap<String, JspPropertyGroup>(), new HashMap<String, TagLibraryInfo>(), new HackInstanceManager());
```
I understand that it is only this portion.
HashMap<String, TagLibraryInfo>()

**Comment by gencube** [comment]
What are the values to be placed within these two variable?
```java
TldsMetaData tldsMetaData = null;
List<TldMetaData> sharedTlds = null;
```

**Comment by gencube** [comment]
Found out from, UndertowDeploymentProcessor.java:
```java
 TldsMetaData tldsMetaData = deploymentUnit.getAttachment(TldsMetaData.ATTACHMENT_KEY);
// and the rabbit holes goes deeper with other dependency.
```
and also from here, as shown by Stuart Douglas:
https://github.com/undertow-io/jastow/blob/master/src/test/java/io/undertow/test/jsp/taglib/TagLibJspTestCase.java
```java
 Map<String, TagLibraryInfo>  tags = new HashMap<>();
        TagLibraryInfo bugTld = new TagLibraryInfo();
        bugTld.setUri("/bug.tld");
        bugTld.setPath("/bug.tld");
        bugTld.setVersion("2.0");
        bugTld.setTlibversion("1.1");
        FunctionInfo functionInfo = new FunctionInfo();
        functionInfo.setName("dummy");
        functionInfo.setFunctionSignature("java.lang.Runtime getRuntime()");
        functionInfo.setFunctionClass("java.lang.Runtime");
        bugTld.addFunctionInfo(functionInfo);
        tags.put("/bug.tld", bugTld);

        // THIS is where I was pointed to by Stuart 
        JspServletBuilder.setupDeployment(builder, new HashMap<String, JspPropertyGroup>(), tags, new HackInstanceManager());
```

There should be a constant value hashmap or a way to load JSTL since it is common standard.
 Map<String, TagLibraryInfo>  tags = new HashMap<>();

**Comment by gencube** [comment]
Hi Thomas, 
What is the status of this issue? 
Since JSTL 1.2 is a standard library, how do I patch that code into Jastow?

**Comment by gencube** [comment]
This code was newly added, BUT error still exist:
```
JspServletBuilder.setupDeployment(builder, new HashMap<String, JspPropertyGroup>(), toJSTL() , new HackInstanceManager());
...
public static Map<String, TagLibraryInfo> toJSTL() {
        Map<String, TagLibraryInfo> tags = new HashMap<>();

        String[][] jstlInfos = {
            {"http://java.sun.com/jstl/core_rt", "c-1_0-rt.tld", "1.0", "1.0"},
            {"http://java.sun.com/jstl/core", "c.tld", "1.0", "1.1"},
            {"http://java.sun.com/jsp/jstl/functions", "fn.tld", "1.0", "1.1"},
            {"http://java.sun.com/jstl/fmt_rt", "fmt-1_0-rt.tld", "1.0", "1.0"},
            {"http://java.sun.com/jstl/fmt", "fmt.tld", "1.0", "1.1"},            
            {"http://java.sun.com/jsp/jstl/sql", "sql.tld", "1.0", "1.1"},
            {"http://java.sun.com/jstl/sql_rt", "sql-1_0-rt.tld", "1.0", "1.1"},            
            {"http://java.sun.com/jsp/jstl/xml", "x.tld", "1.0", "1.1"},
            {"http://java.sun.com/jstl/xml_rt", "x-1_0-rt.tld", "1.0", "1.1"}
        };

        for (String[] jstlinfo : jstlInfos) {
            TagLibraryInfo info = new TagLibraryInfo();
            info.setUri(jstlinfo[0]);
            info.setPath("/META-INF/"+jstlinfo[1]);
            info.setVersion(jstlinfo[2]);
            info.setTlibversion(jstlinfo[3]);
            tags.put("/"+jstlinfo[1], info);
        }

        return tags;
    }
```

**Comment by gencube** [comment]
Manual Construction of TagMap is needed and not an effective approach to loading support JSTL.

**Comment by hofmanndavid** [comment]
I have a working version of tag discovery for jastow. The current caveat is that it depends on jboss-metadata-web and jboss-metadata-common but I can get rid of them and provide a helper to be used while configuring jastow with undertow via `JspServletBuilder.setupDeployment(...)`.

Something like `Map<String, TagLibraryInfo> TldClasspathHelper.find()`

Is this something that will be useful to include in jastow for general use?

**Comment by gencube** [comment]
Sorry for the late reply. The answer is yes.
