### ISSUE TITLE
Malformed URL for tag dependant

### ISSUE THREAD

**Issue by Maldivia** [undertow-io/jastow#25]
The dependants added in [`TagFileLoaderVisitor.visit()`](https://github.com/undertow-io/jastow/blob/master/src/main/java/org/apache/jasper/compiler/TagFileProcessor.java#L653) are invalid URLs, causing `new URL(key)` in [`Compiler.isOutDated()`](https://github.com/undertow-io/jastow/blob/master/src/main/java/org/apache/jasper/compiler/Compiler.java#L491) to fail with `MalformedURLException`, falling back to assuming that they are outdated.

Example path generated: `"jar:/WEB-INF/lib/library.jar!/META-INF/sample.tld"`
Causing the following exception:
```
DEBUG [org.apache.jasper.compiler] (default task-7) Problem accessing resource. Treat as outdated.: java.net.MalformedURLException: invalid url: /WEB-INF/lib/library.jar!/META-INF/sample.tld (java.net.MalformedURLException: no protocol: /WEB-INF/lib/library.jar)
	at java.net.URL.<init>(URL.java:620)
	at java.net.URL.<init>(URL.java:483)
	at java.net.URL.<init>(URL.java:432)
	at org.apache.jasper.compiler.Compiler.isOutDated(Compiler.java:491)
	at org.apache.jasper.compiler.Compiler.isOutDated(Compiler.java:406)
	(...)
```

**Comment by ctomc** [comment]
Do you have some case how to reproduce this?

**Comment by Maldivia** [comment]
Hi, sorry for the delay.

Here's a simple war file, containing a setup that showcase this:
https://www.dropbox.com/s/zc0p229dde4ti0s/tagfile.war

The `test.Test` class simply throws an exception if jsp or tag class was recompiled.

Easiest way to reproduce is to enable the *development* mode, and set `org.apache.jasper.compiler` logging to DEBUG, then simply deploy above and load [http://localhost:8080/tagfile](http://localhost:8080/tagfile) and refresh.

The refresh should show you an exception, indicating that the jsp or tag class was recompiled.
And in the `server.log` you'll see the `MalformedURLException`.
